flowchart TD
%% generated in 0.03s
    examples__frontend["examples.frontend<br/>25 funcs"]
    java__JavaAstExtract["java.JavaAstExtract<br/>12 funcs"]
    python__ast_extract["python.ast_extract<br/>13 funcs"]
    sdk__python["sdk.python<br/>67 funcs"]
    src__diff["src.diff<br/>173 funcs"]
    src__graph["src.graph<br/>115 funcs"]
    python__ast_extract ==>|4| src__diff
    sdk__python -->|2| java__JavaAstExtract
    sdk__python -->|1| src__graph
    sdk__python -->|1| examples__frontend
