flowchart TD
%% generated in 0.03s
    python__ast_extract["python.ast_extract<br/>13 funcs"]
    sdk__python["sdk.python<br/>68 funcs"]
    src__diff["src.diff<br/>181 funcs"]
    src__graph["src.graph<br/>133 funcs"]
    src__synthesis["src.synthesis<br/>290 funcs"]
    sdk__python ==>|6| src__synthesis
    python__ast_extract ==>|4| src__diff
    sdk__python -->|2| src__graph
    python__ast_extract -->|1| src__synthesis
